export const version = '1.10.0';

export const CHANGELOG = [
  {
    version: '1.10.0',
    date: '2026-08-15',
    changes: [
      'THE SPHERE TEST — section 08, and it is the first block in this document that is not a control. Everything before it is a thing you touch; this is a thing you JUDGE, and the whole of it is three fills drawn twice each with nothing to set. Materials moved to 09 and the bill to 10',
      'THREE NEW HANDS: HAND HATCHING, HAND CROSS HATCHING, HAND RANDOM LINES. They are not a re-tune of the bay\'s Hand hatched position — that one breaks the register and stops, which makes a fill look NOISY, and noisy is not hand-made. What a hand does is a list, and every item on it is something a loop does not do',
      'IT DOES NOT SPACE EVENLY, and that is the one that mattered most: an unvarying pitch is a louder machine tell than straightness ever was, so every family is jittered by a third of its own spacing before any wobble is applied. Wobble alone was tried first and reads as a shaky machine',
      'IT DOES NOT COME BACK AT THE SAME ANGLE (each pass drifts a couple of degrees off the last), IT DOES NOT STOP ON THE LINE (a stroke overshoots the boundary or pulls up short, never by the same amount twice), and IT RE-GRIPS — past about 16mm the wrist runs out of travel, so a long fill contains no edge-to-edge strokes at all',
      'TONE IS BUILT BY GOING BACK OVER, not by drawing a grey: four passes, each confined to what is already darker than the last. Every threshold is dithered with noise, because a clean one draws a CONTOUR MAP of the lighting — the fill bands into visible isolines, which is the one thing that never happens by hand',
      'A FLOOD IS NOT A DARK. Four interleaved passes at pitch s put the darkest tone at s/4, so s has to stay four nibs clear of the crossing or the terminator turns into a solid black disc. Same crossing the hatch bay marks in red on its spacing knob, met again from the other side',
      'THE STROKES FOLLOW THE FORM on the ball, built as latitude circles about an axis tilted behind the screen plane — not as a rotated grid. A grid is right for a flat fill and silently wrong on a sphere: it has no idea where the surface turns',
      'THE AXIS IS AIMED DOWN THE LIGHT, which is the geometric problem this block had to solve rather than tune around. Every axis has a pole on the front of the ball and a place where its circles shrink to a point; put either in the middle of the shading and there is a visible whirlpool in the fill. They cannot be removed, only placed — at 20° behind the plane both land near 0.94R, and the light\'s own screen direction puts the highlight at 0.79R. Aim the axis down the light and the blank cap round the pole IS the highlight and the cap opposite it IS the reflected-light rim. Both are places a hand leaves paper anyway',
      'THE BALL IS THE TONE TEST because it is the one shape whose correct answer everybody already knows. Lambert alone draws a shaded DISC — what makes a sphere is the terminator being darker than the silhouette and the table\'s BOUNCE lifting the lower rim, occluded near the contact so the contact itself stays black. The cast shadow is the only thing saying "table"; there is no horizon line, because a drawn line would be a second object competing with the one being tested',
      'A SECOND SPECIMEN PER HAND, and it is not a bonus: a circle has no corner, no neck and no concave anything, so a fill can be perfect on a ball and come apart the first time it meets a real outline. The flat SHAPE carries no shading at all, one density edge to edge, and what is read there is the boundary — where the strokes stop, and whether they stop in a line',
      'COLUMNS ARE HANDS AND ROWS ARE TESTS, which is the only arrangement where both comparisons are adjacent: down a column is one hand against two problems, across a row is three hands against one',
      'EVERY MARK IS GEOMETRY IN MILLIMETRES. No filter, no blur, no fill anywhere in the block — the viewBox is measured off the element at 96/25.4 exactly as the hatch bay measures its own, so a 0.25 nib on screen is a 0.25 nib on paper and the same paths go out to an SVG and onto the plotter with no rescale. That is the only condition under which a specimen is worth looking at',
      'THE SPECIMEN GLASS KEEPS ITS REFLECTION AND LOSES ITS SCANLINES — the one place this block departs from .screen, and not a preference. The haze is a 1-in-3px horizontal rule and the thing behind it is a fill made of rules a few tenths apart; they beat, and the moire lands exactly on the property being judged. A display that adds texture to the specimen is a filter, not a display',
      'ONE PATH ELEMENT PER SPECIMEN, not one per stroke. A plotter reads movetos, not the DOM, and the random hand emits about five thousand of them',
      'Three more .eng engravings — hatching, cross hatching, random lines — each drawn as its own marks rather than as a picture of them',
      'NO CONTROLS, deliberately, beyond NEW SHEET which re-rolls every seed. Three hands are three answers to one question and what is being asked is which is right; a knob on it would invite tuning before judging. Which of the constants become parameters is recorded in FEATURES-REQUEST, not decided here',
    ],
  },
  {
    version: '1.9.0',
    date: '2026-08-15',
    changes: [
      'THE HATCH BAY — the first COMPOUND control in the language. Everything before it is one control on one row, and hatching was five of those: same shape, same green number, nothing saying which one you turn to change how the drawing looks',
      'It is built round a SPECIMEN, because the refs all put the display in among the controls that feed it — the EQ-200 draws the curve its ten faders make. You judge 0,6 by seeing how dense 0,6 is, not by reading it',
      'THE SPECIMEN DRAWS A LIT SPHERE, not a swatch. A rectangle of even hatch shows the SPACING and hides everything else — and what hatching is actually for is TONE: the same pen at the same angle making light and dark by how much paper it leaves. So it draws the subject every hatching exercise starts with, lit from the same corner as the panel, sitting on its own cast shadow. The field grew to 248px and the bay to 520px to give it room',
      'Tone comes out of WHICH PASSES REACH A POINT, not out of pressure: every scanline carries a threshold and only puts ink down where the drawing is darker than that, so light areas are reached by a few passes and dark areas by all of them. The thresholds walk the golden ratio rather than a cycle, so the passes interleave instead of banding into visible tiers — which is the one thing that gives away a machine-made hatch',
      'CROSSED now means what it means on paper: the second pass thresholds live in the top half of the range, so it only works the parts that are still not dark enough. SERPENTINE chains the runs on a pass into one path and draws the connector between them, which is also why a serpentine fill cannot make a clean highlight — the meander has to cross the light to reach the next dark. HAND HATCHED drifts its threshold and sits each pass off its own track, so no two passes agree where a tone ends',
      'A floor of 0.085 on the lit side, because at zero the highlight gets no strokes at all and the ball dissolves into the paper with no edge. A few sparse passes across the light is what a hand does and it is what makes the silhouette read',
      'The rebuild is coalesced on a frame — a tone-driven hatch is thousands of samples and a knob drag fires far more often than the screen refreshes',
      'The specimen is SVG in real millimetres — the viewBox is measured off the element and converted at 96/25.4, so one user unit is one mm and what is on screen is what plots. DOM, not canvas: it takes the bay\'s ::after glass for free. That decides hatch only, NOT the gizmo or the screen — the open question at the foot of FEATURES-REQUEST stands',
      'NEW PRIMITIVE — .plate, the language\'s first floating surface. Everything else in the document is bolted into a chassis; this one positions itself against whatever summoned it, sits above the panel and goes away. Same metal as a .box with two differences, both about elevation: a harder and shorter cast shadow, and 1px of black all the way round, because a lifted edge has a dark side wherever the lamp is. Menus, tooltips and the rotary\'s popup inherit it',
      'NEW PRIMITIVE — .picker, and it replaces the one surface the OS still drew. input[type=color] renders its popup in browser chrome and no CSS reaches it, so touching a colour produced a bright system sheet on a machined panel: the exact moment every other primitive exists to avoid. Field behind the same glass as any display, hue on a real fader with the knurled cap and a scale at the six primaries, one lit .lcd window with editable R/G/B and hex instead of three white boxes, eyedropper as a .key that hides itself where the API is absent, and a well of recents built from the same .pencap the ink rail uses. Dark on purpose — a picker is the one place the panel must disappear so the colour can be judged',
      'The native input is kept as the VALUE and never as the surface, so swapping the picker in changes the caller and nothing downstream. openPicker() is a primitive, not a bay feature: the hatch bay\'s pens call it and its own Materials tile calls it, which is what makes it one',
      'NOT built, and it is the last piece: the plate does not trap focus. Escape and click-outside close it, but Tab still walks into the page behind. Recorded in FEATURES-REQUEST against .plate rather than .picker, because it decides the pattern for every floating surface after this',
      'THE THREE PARAMETERS ARE THREE KNOBS, which is what this document\'s own rule already said — "every slider that sets a quantity became a knob; a length stays a fader". Pen, spacing and angle are three single quantities and none is a span with two ends you compare, so all three were faders in defiance of a rule the page states twice. One row of 46px knobs also costs a third of the height three param strips did',
      'THE TYPE SELECTOR IS THE ROTARY, not a bar of keys: Parallel / Crossed / Hand hatched / Serpentine. A row of keys shows four labels and makes you infer they are one choice; a selector switch has one lever on one detent, so the fact that they are alternatives is in the object rather than in the reading',
      'FOUR HATCH TYPES: PARALLEL, SERPENTINE, CROSSED, HAND HATCHED. They are four different PATHS, not four textures — parallel lifts the pen at the end of every pass, serpentine does not and is one continuous stroke, crossed is a second pass at 90°, hand hatched breaks the register so the fill has no readable direction',
      'The lines are generated in world space and clipped to the sheet (Liang-Barsky) rather than drawn on an over-sized grid and rotated. That is not tidiness: a serpentine IS its turnarounds, and on an over-sized grid every turnaround falls off the paper — it would have rendered as PARALLEL under a different name on the dial. Clipped, every endpoint lands on the boundary where a real fill puts them, and SERPENTINE emits exactly one moveto where the other three emit one per pass',
      'PEN, SPACING AND ANGLE ARE INDEPENDENT. An earlier build had the pen drag spacing along to hold a nib ratio — a tidy idea and the wrong one, because it means one control silently edits another and a value you set by hand stops being the value you set. Three settings, three knobs, no hidden wiring',
      'SPACING UNDER THE NIB IS NOT REPORTED, because it is not an error. The strokes overlap and the sheet fills solid on its own — that is a fill, and a fill is something you ask for. An earlier build lit a red legend and turned the spacing arc red, framing a legitimate result as a fault; the specimen already shows exactly what happens, which is the whole job of a specimen',
      'THE GROUND IS PAPER NOW. It was near-black, which worked for exactly as long as the ink was orange — and the case has BLACK in it, which is the pen you own most of. Black on black is nothing and grey on black is worse, because it looks like it is working. Same argument the colour picker entry makes: the surface a colour is judged against cannot compete with it',
      'THE INK RAIL IS A CASE, so it is full of SLOTS — three pens you own whatever you draw (black, grey, white) and six empty ones. A rail that stops after the pens you happen to have reads as a list that ran out; a case reads as a case, and an empty slot is an invitation rather than an absence. It is also the honest way to say "any colour": you put one in',
      'AN EMPTY SLOT IS A HOLE, not a faded pen. The wrong build is a cap at low opacity, which reads as broken or disabled — a slot with nothing in it is a piece of the CASE: a shallow milled well, shorter than a cap because no cap is standing in it, with the same two hairlines every other recess has, and no colour at all because it does not have one yet. It lights its own rim on hover rather than lifting, because a hole cannot come towards you',
      'Empty opens the picker on the FIRST click, because there is no pen to choose yet — filling it is choosing it. A filled slot selects first and refills on the second, so choosing a pen never costs a plate. The slots are spread rather than packed, so the rail ends where the panel ends however many pens are in it',
      'THE STOCK IS TONED (#BEB5A3), because the case has a WHITE pen in it. White on cream is not a subtle result, it is no result — the sheet would look broken rather than look like white ink. Toned stock is what you reach for when you plot white, and it is the one ground where black, grey and white all read at once: contrast against the sheet is 8.7 / 2.9 / 2.0, and grey separates from both its neighbours',
      'fader() exposes .set(), the handle knob() already had, so one control can move another',
      'COLOUR IS A PIPETTE OF INK. A cap is painted on the outside and hides its ink; a glass tube is the other way round and you are looking THROUGH glass AT the ink, which is what a swatch is claiming to show you anyway',
      'THREE SILHOUETTES BEFORE IT READ AS ONE. A pen cap read as a battery. A single tapered tube read as a marker tip. Both missed the thing that identifies a pipette at a glance — A BULB ON A LONG SLENDER STEM — and the proportion is the whole message: roughly one part bulb to two parts glass, parallel for most of its length, pulled out SHORT AND LATE at the tip. A taper that starts halfway is a marker',
      'AND THE BULB IS GLASS, NOT RUBBER, corrected against the real object: the black-teat dropper is the chemistry-set one, the one actually on the desk is drawn glass all the way through with a swelling IN it rather than a fitting ON it',
      'That inverted the shading, and the first pass had it backwards. Dark walls were reasoned from "the edge is more ink to look through" — true of a solid cylinder of liquid, false of a TUBE, where what is at the edge is WALL, and a lit glass wall is the brightest thing on the object. The ink is a core, not a skin; the glass is bright at both edges; the meniscus is a curve because liquid in a narrow tube is; and the specular runs the full height because it is on the OUTSIDE and does not care where the liquid stops',
      'Built as two elements rather than one outline, so the bulb can be a rounded swelling and the stem a clipped tube. The clip-path means the cast shadow is a drop-shadow filter — a box-shadow would be clipped away with everything else, and a filter follows the shape, which is what a shadow does anyway',
      'AN EMPTY SLOT IS STILL A HOLE, not an empty tube. Once the pens are glass the obvious move is an empty one, and it is wrong: an empty tube is a pen you own that has run out, which is a different fact from a slot you have never filled',
      'Min stroke and Join reach went into a recess below the fold. They are set once per plotter; five identical rows was itself most of why the panel was sad',
      'NEW PRIMITIVE — .eng, the engraved ICON. The language had engraved TYPE and nothing engraved that is a SHAPE, so every icon was a flat monoline glyph laid on the metal: the sticker failure the file already names about a centred highlight. Stroke in the panel\'s shadow colour, one 1px light line under it, never white and never currentColor — an engraving does not change colour when its row is selected, because it is a hole. Six of them so far; every label row in the language can have one now',
      'knob() takes an optional detents array — the angle knob notches at 0 / 45 / 90 / 135 / 180. Same idea the centre fader already had: an angle of 45° is a place, not a value you approach',
      'REMOVED the SLIDER → KNOB A/B card from 04. Sections renumbered: the hatch bay is 07, Materials 08, the bill 09',
    ],
  },
  {
    version: '1.8.0',
    date: '2026-08-15',
    changes: [
      'MATERIALS stops over-claiming. The lede promised that nine primitives carry all six components and that every control on the page is one of them at a size — a completeness claim nobody re-counts when they add a tile, and it read "nine" while the grid held thirteen',
      'The count is now written by the tiles themselves. Adding an entry to the array is the only edit there is; the sentence cannot drift again',
      'Three primitives that were on the page and had no tile: READOUT (the .lcd, used 4× — a lit window cut into the case, phosphor digits, and .dim as an off state that is powered rather than dark), MICRO KEY (22px and recessed, because duplicate and delete must not invite the thumb; delete is the only red in the document and only on hover), KNURLED CHEVRON (the thing you flick — shown at its real 20px, since the knurl is tuned against an 11px glyph and enlarging it would show a texture the document does not have)',
      'Both new key tiles are live for the same reason the fader ones are: a micro key\'s whole content is its hover and a chevron\'s is its flick, so a static sample shows the half that does not matter',
      'The knob/fader rule was stated once, in a comment under .knob, and was therefore invisible from the section built to teach the primitives — a reader concluded the language\'s answer to a slider is "turn it into a knob". It is in the knob tile now: a quantity is a knob, a length stays a fader',
      'FIX — .chev had no position:relative, so the chamfer ring that .chev.open::after draws resolved against .row and was clipped away by its overflow. The one control the chamfer rule names by name was the one control not getting one',
    ],
  },
  {
    version: '1.7.0',
    date: '2026-08-15',
    changes: [
      'The fader family, from the refs: the EQ-200, the TX-6, the K.O.II and the Sidekick are all banks of ONE-cap faders, and the document only had the two-cap range one, which is the exception, not the type',
      'fader() — one factory, three forms, because they differ in two things only: where the lit fill starts and which way the slot runs. LEVEL fills from the end of the slot to the cap. CENTRE fills from the middle out to whichever side, for a value that is an offset rather than an amount. VERTICAL is the same control stood up, with the readout on top and the legend at the foot',
      'The centre form DETENTS: inside 3% of the middle the cap snaps to zero and the scale carries a full-height tick there, the way a real centre-detent pot has a notch cut in its track. Zero is a place you can find without looking',
      'All three share the range fader\'s geometry — a cap centre at t sits at t*100% - (t-.5)*17px — so a cap stays inside its slot at both ends without the value lying about where it is. Track takes every pointer event and the cap comes to the click; wheel and arrows work, shift for fine',
      'Three material tiles for them: FADER · ONE CAP, FADER · CENTRE DETENT, FADER · VERTICAL BANK (three of them, since the reason vertical exists is that a bank of caps makes a profile you read across)',
    ],
  },
  {
    version: '1.6.1',
    date: '2026-08-15',
    changes: [
      'The bright skin came back in the 1.6.0 commit and is removed again: 296 lines of [data-skin="light"], the .skin-switch rules, the empty switch element (its script had already gone, so the page was rendering a stray fixed well top-right) and the restored skin() IIFE that sat directly under the comment explaining why it was gone',
      'MATERIALS was missing the fader, the one control the lede promises by name: every slider that set a quantity became a knob, except a length, which stays a fader. It is there now, live, built by the editor\'s own rangeFader with the same numbers',
      'Its tile spans two columns. A fader sampled in a 232px column leaves the track about 90px once the label and the readout are in, which is not a length, it is a stub. Tiles take an optional class as a fourth field for this',
      'NOTE: physical-ui.css.bak is tracked and still contains the whole bright skin. It is a 1750-line copy of the pre-rename build; left alone here because another agent may be relying on it, but it is where the light mode will come back from next',
    ],
  },
  {
    version: '1.6.0',
    date: '2026-08-15',
    changes: [
      'The bright skin is removed — 336 lines of [data-skin="light"] overrides, the DARK / LIGHT switch and its script. Every effect in this document is light modelling against a dark body: a cap is lighter than its case, a well is darker, and a recess is made by taking light away. That cannot be inverted, only rewritten, so the pale build was a second set of hand-tuned numbers drifting from the first every time either was touched. One material, one set of numbers',
      'The exploration keeps its external stylesheet: physical-ui.css stays a file, dark only',
      'The piano wells (page switcher and editor tabs) get the floor the bay was given back at 1.4 and never shared: #17191d → #1e2126 instead of near-black. A key\'s skirt is #0d0e10, so on a #0a0b0d floor the one part that proves a cap has a body was invisible and the key read as a grey rectangle printed on black. Inset shadow softened to .8 to match',
      'The language has a name: SKEW. It is the word the hand types when it means skeuomorphic, and it is also the trick itself — a flat plane tilted into depth, lit from one lamp above left, nothing actually raised. In the page as targz-skew-design-system',
      'The MOMENTARY VS LATCHING tile was two spans wearing the key classes, under a caption promising that one springs back and the other holds: a sample that could not do the thing it was a sample of. They come from the same key factory as the nav bar now, and both work',
      'Its glyphs were 24px in a 38px cap, leaving 7px of face — on the lit one the sun\'s rays ran into the walls and the orange stopped reading as a legend and became the button\'s colour. 18px now, the nav bar\'s 16-in-34 ratio at this size',
      'The MILLED WELL material tile was demonstrating the fault it documents: the tile stage was #101114, darker than the well cut into it, so the sample was a lighter rectangle on a dark ground. The stage is case metal now, the well sample carries the real recipe, and the caption states the floor rule',
    ],
  },
  {
    version: '1.5.1',
    date: '2026-08-15',
    changes: [
      'Tool palette: keys were 5px apart, which is not 5px of daylight — each raised cap lays a 3px hard skirt plus its blur underneath, and a pressed cap drops 2px further into the gap below it. Pan / Turn / Select were touching. Now 10px, in line with the keypad\'s 11px between stacked rows, and the palette padding goes 7 → 8px so the outer margin does not read as tighter than the inner one',
      'TOOL caption sits 6px above the first key rather than 4px, so the label is not closer to the key than the keys are to each other',
      'Editor tab strip had the same fault worse: 3px between tabs, each laying a 2px skirt, so Letters / Place / Size / Drop / Shade were one object with lines drawn on it. 7px now, and the strip padding 4 → 5px',
      'The editor tab no longer travels. A 26px cap falling into a strip this tight puts its shadow on the neighbour, and there is no room for the fall to read as a fall — it still goes in (recess, chamfer, lamp), it just does not move',
    ],
  },
  {
    version: '1.5.0',
    date: '2026-08-15',
    changes: [
      'Physical UI exploration: the pressed recipe is now two tokens in :root — --recess (the four sharp walls plus the lit lip) and --chamfer (the directional, concave-polarity ring). Five copies of it across switches, keys, tabs, chips and chevrons was five things that drift apart the next time one is tuned',
      'Every toggle in the document now uses it: layer switches, stroke switches, the ALL masters, nav bar latches, editor tabs, the page switcher, view keys, folder chips and chevrons. None declares a fill — each inherits its own raised face, so a pressed cap stays the same object as the cap beside it',
      'Travel normalised: 2px on the big keys, 1px on the small. A tab falling 4px was travelling further than the gap to its neighbour',
      'Fixed: .keypad .pkey and .piano.sm .pkey re-declared box-shadow at the same specificity as the pressed rule but later in the file, so the view keys and editor tabs kept their RAISED shadow when down and only the label changed colour. The size overrides are scoped to :not(.is-down):not(:active) now',
      'Fixed: .chev.open\'s box-shadow ended in a stray comma, making the whole declaration invalid — the open chevron had had no shadow at all',
      'Toggles get the momentary key\'s actuation surge when they engage, and only when they engage: flipping a switch off is a circuit opening, there is nothing to surge. Reuses the same keyframe rather than a second one, since two nearly-identical surges read as one done badly',
      'Pan / Turn / Select moved out of the viewport into their own tool palette. Everything else in that panel answers where the camera is; those three answer what the mouse does, which stays true while you are not looking at the viewport at all',
      'Focus: removed eleven accent outlines and answered :focus-visible explicitly — deleting them had only uncovered Chrome\'s own white-blue default. One hairline everywhere, 1px in the panel\'s orange, plus a brightness lift on the control itself',
      'Removed the colour dot from numbered layer rows; the ALL row keeps its jewel, which wears the whole palette',
    ],
  },
  {
    version: '1.4.2',
    date: '2026-08-15',
    changes: [
      'Physical UI exploration: the chamfer round a pressed switch is now a ring with a direction, not a hairline. A cutout edge is broken all the way round and is not equally lit anywhere — it flares where it faces the lamp and dies as it turns away — and a box-shadow, being the same value the whole way round, always reads as a drawn outline instead',
      'Corrected its polarity, which was the actual bug: the ring was bright top-left and dark bottom-right, which is a DOME. A chamfer diving into a hole is the opposite — its upper edge tilts away from the light and sits in shadow, its lower edge tilts toward it and catches. It was also arguing with the walls inside the cap, which were already right, and a bevel saying "out" wrapped around a recess saying "in" resolves as a raised button every time',
      'Pressed shadow +20% in geometry (offsets and blur, alphas untouched), and the pressed legend is back to full size',
      'Removed the colour dot from numbered layer rows — the light pipe on the leading edge is the same fact, said better and 6px away. The ALL row keeps its jewel, which wears the whole palette',
    ],
  },
  {
    version: '1.4.1',
    date: '2026-08-15',
    changes: [
      'Physical UI exploration: the pressed switch rebuilt. It declares no fill of its own — it inherits the raised cap\'s, so up and down cannot drift apart, and the recess is drawn entirely by inset walls. Every earlier attempt at a separate pressed colour was drawing shade with paint, and a darker cap has nothing left for a shadow to take away',
      'Raised the cap into real grey. Shadow is a difference, and a near-black face left the recess nowhere to fall — the change that makes the pressed state read is a change to the unpressed one',
      'Shadow on all four walls, not just the top: a hole has sides, and at 24px the sides are most of what you see of it',
      'Sharpened it — blur radii 6-12px down to 1-4px. A wall two pixels from the face cannot throw a shade that has softened over that distance; 12px of blur at full black is a cap sitting in fog',
      'Travel down to 1px. Two was a third of the row gap, enough that toggling looked like the row twitched',
      'The legend scales to 0.9 when the cap is down — a face further from the eye subtends a smaller angle. Too small to notice as a change, which is the point',
      'One legend per switch: the plain drawing at normal weight, never struck through or greyed. The cap position already says on or off, and a slashed grey icon reads as disabled',
      'MIXED is now the pressed state with a WHITE legend, not an intermediate height. A master whose column is half on is not half-pressed — the thing it commands is engaged, just not everywhere. Down means it is happening; the colour says how completely, and white against orange is a brightness difference that survives with no colour vision',
      'Brightened the bay, the stroke strip and the row faces to match. A recess is the case seen deeper, not a hole into space — darker than the surface, not black, with the inset shadow doing the work',
      'Rotary selector: removed the detent tick marks entirely. The tip already says where the switch is, and a second mark a few pixels away is another thing to read at the moment you are reading the tip',
      'Knobs and the selector now turn clockwise on a downward drag, and the wheel follows; arrow keys stay conventional so the ARIA slider contract holds',
    ],
  },
  {
    version: '1.4.0',
    date: '2026-08-15',
    changes: [
      'New document explorations/physical-ui-layers.html — a "what if the language were hardware" study. It is an EXPLORATION, not part of the system: index.html is untouched and none of these tokens exist there',
      'Six shipping components redrawn in the skeuomorphic register, each with its real anatomy: the Portrait-Typo layer dock (lifted control-for-control from its ui.js), the nav bar, the page switcher, the layer editor, the viewport and a Launchpad project card',
      'Buttons are objects with a body: a skirt, a cast shadow and real travel. Momentary keys spring back and pulse once; latching keys hold the same position a finger would, which is the distinction flat UI has no way to make',
      'Latched, pressed and open all share one recipe — the cap keeps its own colour, the gradient inverts, a hard black inset runs along the top and a hairline of light along the bottom, and only the legend lights. Three-state switches sit at three physical heights (up / half / down), so the state reads in greyscale',
      'One legend per switch: the plain drawing at normal weight, never struck through or dimmed, since the cap position already says on or off and a slashed grey icon reads as disabled',
      'Sliders that set a quantity became knobs — 270° of travel, an SVG-stroked value arc (a conic gradient behind a CSS mask aliases on three edges), a pointer, drag/wheel/keys, and a bipolar mode that grows from 12 o\'clock. Drag down turns clockwise',
      'Zone from / Zone to became ONE range fader, because the value is one length: cut slot, engraved scale, two waisted caps that cannot cross, a hatched band between them',
      'The Place-from dropdown became a rotary selector: a pale teardrop lever, positions fanned into 76° with their names as a vertical list, leader lines absorbing the angle mismatch',
      'The editor panel bulges around that selector — rounded rectangle unioned with a lobe and joined by tangent fillets, as one clip-path on one element, so the fill cannot seam. Its drop shadow is a filter on a wrapper, because a box-shadow is cast by the border-box and would cut the bulge in half',
      'Glow is spent only on things that emit: light pipes, LED readouts and the big illuminated action keys',
      'Closes with the bill — what the language buys, and what it costs (dark-only, paint cost per row, small type against grain, and that it out-shouts the drawing)',
    ],
  },
  {
    version: '1.3.0',
    date: '2026-08-06',
    changes: [
      'Canvas, grid & rulers (section 03): replaced the static "warm grid" description with how it actually works — the grid is derived from the sheet, not a fixed 40px CSS pattern',
      'Documented the division formula round(max(canvasW, canvasH) / 60) clamped to 4-30, so grid lines always land on the paper edges and continue to the window edges',
      'Documented the size readout: bottom and right rulers pinned to the sheet, a tick per division but only the two ends labelled, in millimetres',
      'Recorded that the Y axis is inverted (paperH - mm) so the origin is bottom-left, matching the plotter bed',
      'Added a demo showing an A1 square sheet at 594 x 594 mm with its grid and both rulers',
    ],
  },
  {
    version: '1.2.0',
    date: '2026-08-06',
    changes: [
      'Side panel (section 06): rewritten as a Tweakpane 4 spec — the hand-drawn panels were never Tweakpane, which is what every app actually ships. Adds a prominent "do not hand-build this" callout, a faithful replica of a skinned pane, a widget anatomy table mapped to the --tp-* variables, placement rules, and the full skin block to copy',
      'Nav bar (section 07): replaced the old Bottom Dock with the glass nav bar as actually shipped — 40px items, popover menus with kbd shortcuts, separator, status readout — plus a full spec list',
      'Logs (section 10): the log is now an event, not a surface — silent by default, a transient toast above the nav bar, and an on-demand history in a nav bar popover, with repeat collapsing, dwell rules and an unread dot',
      'Tab bar (section 11): added the white pill page switcher — demo, spec and states. Active is an --tg-orange-soft fill with an --tg-orange label; focus is a 3px orange halo, never the browser default',
      'Section 11 renamed to "Tab bar & app header"; the docked app header is kept for windowed tools',
      'Console is now bright — white surface, hairline border, orange $ prompt — instead of the black block',
      'Scoped the console to streamed output from external processes (vpype, plotter drivers)',
      'Added a contents rail with scroll-spy, built from the sections at runtime',
      'Added glass tokens: --tg-glass, --tg-glass-border, --tg-glass-hover, --tg-shadow-float, --tg-shadow-pop',
      'Everything else in the document is unchanged',
    ],
  },
  {
    version: '1.1.0',
    date: '2026-05-01',
    changes: [
      'New design system created with Claude design (targz Design System.html)',
      'Remove previous design-system.html (no longer relevant)',
    ],
  },
];
