export const version = '1.17.0';

export const CHANGELOG = [
  {
    version: '1.17.0',
    date: '2026-08-16',
    changes: [
      'THE WHEEL ROLLS WITH THE DRUM. It was a still picture of a knurl beside a list that moved, which is the one thing a wheel must not be — the surface travels R·θ per detent, 17.9px at an 18px pitch and 18°, so the teeth now move exactly as far as the names do, on the same spring the names settle on. A wheel and the thing it drives have to agree or neither is believable',
      'ONLY THE TEETH MOVE. Two background layers and the split is the whole point: the knurl is a property of the CYLINDER and travels with it, the crown highlight is where the LAMP falls and stays put however far the thing has turned. Slide both and it stops being a wheel and becomes a conveyor belt',
      'THE TOOTH PITCH IS 3.2px AND NOT 3px, on purpose. One detent rolls the surface 17.85px, which at a 3px pitch is very nearly six whole teeth — the pattern would land identical every time, so the only movement you could ever see was during the tween and a wheel turned five times would look untouched. At 3.2 it crosses 5.58 teeth and lands 1.85px out, two thirds of a tooth, so the motion reads AND the resting state remembers it',
    ],
  },
  {
    version: '1.16.0',
    date: '2026-08-16',
    changes: [
      'NEW PRIMITIVE — the DRUM, for a list the dial cannot hold. The rotary\'s fan is a fixed 80°, so its detents run from 27° apart at four names to 9° at ten, and a real selector switch detents at about 30° — the positions stop being AIMABLE long before the names stop fitting. Six is the ceiling and the 3D page had already passed it',
      'It gives up the rotary\'s claim to show every position, and gives it up honestly. A drum shows the NEIGHBOURHOOD — the one you are on, lit, in a milled window, with the names either side curving away. A <select> is a list that HIDES; a drum is a list you are looking at part of, and the part you cannot see is visibly still there, rolling round the back of the cylinder',
      'IT IS A REAL CYLINDER, not a scaled list: each name is rotated about the drum\'s axis and pushed out to its radius in 3D, so the spacing compresses towards the edges and the top and bottom rows FALL AWAY rather than fading. A list with an opacity ramp on it is a list with an opacity ramp on it, and the eye knows',
      'The geometry is solved rather than guessed — a name k steps out projects to R·sin(kθ), so how many you SEE is fixed by the window height and not by how many you draw. 18° at an 18px pitch gives a 57px radius, which puts the fifth name past a 76px window: five visible, the sixth clipped, the right neighbourhood for a list of ten',
      'FIX — the first build magnified everything. Items sat at translateZ(+R), 57px toward the viewer against a 200px perspective, so the front row was scaled 1.4× and every name came out sliced down both sides. The whole drum is pushed back by its own radius now, so the row you are reading lands at z=0 at its true size',
      'FIX — you turn it by the WHEEL, not by the names. Dragging across the window was dragging across TEXT, so the browser started selecting it: a blue smear over the list with the drum moving underneath. The names are not a handle, they are the thing being read. A click still picks a name, because a click is not a drag',
      'THE WHEEL WAS SHADED THE WRONG WAY ROUND. The drum\'s axis is horizontal, so its edge turns away at the TOP and BOTTOM and is broadest across the middle — the shading has to run vertically to match, and it ran horizontally, which shades a cylinder lying the other way and contradicts the very list rolling beside it. 24px wide now, lit crown just above centre, and the teeth die at the ends because on a real wheel they crowd together as the surface turns out of sight',
      'THE WHEEL COMES UP THROUGH A CUT. It was butted against the window, which reads as two panels side by side rather than a cylinder in a slot: hard dark walls closing over it, the far wall catching the room at the bottom, a chamfer on the cut edge, and a lit line on the CASE ABOVE the opening — a recess is dark inside its top wall, but the flat face it is cut into is the part facing the lamp most directly, and without that line the drum had no top at all',
      'AND THE WHOLE ASSEMBLY DROPS INTO A MILLED WELL with 8px of floor showing all round. A recess is read from its FLOOR, not its walls, so a well with no floor showing is not a well, it is a border',
      'BLOCKED BETWEEN NOTCHES, on purpose. A mouse click and a trackpad flick are not the same event: a wheel sends one big delta per notch, a trackpad a stream of small ones, so accumulating everything fired twice per mouse click and stepping per event ran the list past. A big delta IS a notch and lands at once; small ones are added up until they are worth one — and both pass a 70ms lockout, which is about as fast as a thumb can index a real wheel. The lockout is on the GESTURE and not on set(), because a tab switch writing six controls must land immediately and silently',
      'AND THE DIRECTION IS INVERTED, because you are turning a cylinder rather than scrolling a list. Push down on the face of a wheel and its top rolls away from you, so the names come UP past the window. Matching the scrollbar convention would mean the drum turning the opposite way to the thumb on it',
      'THE DETENT MAKES A NOISE, because a detent IS a noise. This is the one control whose defining feature — the notch it drops into — has no visual at all: you feel a detent, and failing that you hear it. Synthesised rather than sampled, a 40ms chirp falling 2.2kHz to 700Hz through an exponential gain, built lazily on the first turn because an AudioContext made before a gesture is one the browser suspends. It fails silently where audio is blocked and the drum still works',
      'Plus the two visual halves of a notch: the name OVERSHOOTS and settles, because one that slides to its place has been dragged there and one that goes slightly past has DROPPED INTO something — and the case takes the knock, the detent line brightening for 90ms',
      'FIX — the rotary\'s box grows with its list. It was a fixed 130px, which fits six names at 22px apart and silently clipped the seventh; the column is centred, so the overflow went UP as well as down and the first name landed on the caption above the bay. Growing the box does not raise the ceiling — the detents are still the limit — it just stops the failure being invisible',
    ],
  },
  {
    version: '1.15.0',
    date: '2026-08-16',
    changes: [
      'A STRUCK LEGEND, NOT A FADED ONE, on a surface that is not drawn. Dimming says "this key is unavailable", which is the opposite of true — an undrawn surface is still fully editable and you often want to set one up BEFORE switching it on. A strike says the name is still there and the MARK IS NOT: the proof-reader\'s gesture, and the only one that means removed rather than disabled. The line takes the key\'s own colour, so an off tab that is down strikes in the lamp colour and one that is up strikes in grey',
      'THE LAMPS GO OUT on a surface that is not drawn. Every lit thing on the bay means one thing — this is going to be plotted — and on a struck surface none of it is true. ONE FILTER, NOT TWENTY OVERRIDES: the lamps are spread across knob arcs, fader fills, cap indicators, readouts and the ink lamp, and half of them hard-code their colour, so hunting them one by one would miss some and go stale. The controls stay LIVE and only their light goes, and the tab strip is excluded, because you have to be able to reach the tab that turns it back on',
      'FIX — STROKE COULD NOT BE SWITCHED OFF. It was given no state at all, on the reasoning that a contour has no hatch: true, and it does not follow. A contour is still a MARK — it has a pen, it has an ink, and you can decide not to draw it. Leaving it stateless made the one surface on the strip that could not be turned off, which is not a rule anybody would have written down',
      'FIX — AND STROKE HAD NO PREVIEW, for the same bad reason. The surface has no FILL, which is not the same as having no MARK: what a contour plots is the outline at this pen and this ink, and that is exactly what you go to the tab to set. Both sheets draw it now — the ball\'s silhouette, and both of the blob\'s edges, because anything that draws the boundary draws two of them or it is drawing a lie',
      'And `hatches:false` now dims only the four controls that fill an AREA. Pen and ink stay live, because a contour has both — dimming the whole row made the one tab where you set a line\'s weight the one tab where you could not touch anything',
      'FOLLOW THE OBJECT TAKES THE ANGLE KNOB OVER rather than reinterpreting it. An earlier build kept the knob live and made it an OFFSET from the object, which works and asks you to hold two frames of reference in your head to read one number. Two controls steering one value is a panel where whichever you touched last wins and neither says so — so the knob goes dim, and the toggle is not a seventh setting but who decides the sixth',
      'ONE GLYPH FOR FOLLOW, not two. It had a generic box icon on the switch and a separate engraved protractor beside it: two marks competing to explain one toggle and neither saying "the hatch turns with the shape". Now a tilted body with its fill tilted to match — one shape, three strokes inside it, same angle — at 15px in a 26px cap, because it is the only mark on that row',
      'THE INK RAIL IS NINE IDENTICAL SLOTS AND ONE LAMP. The unselected caps were as proud as the one in hand and only a light apart from it, so the rail read as nine equally-live pens and the eye had to hunt. They sit down in the case now: the recess recipe with all four hairlines inverted — hard near-black inside the top, the wall shading from it, a faint light inside the BOTTOM because that is the wall the room reaches, a lit lip outside below, and no cast shadow at all, because a hole does not throw one. Plus the directional chamfer every seated control here gets',
      'AND SELECTION IS THE LAMP, AND ONLY THE LAMP. Three other signals were tried and all three were redundant: the selected cap was bigger, brighter, and its core was inverted. Each is a second thing to notice that means the thing you already noticed, and the cost is not clutter — it is that the rail stops being a row of nine LIKE OBJECTS. A pen case is nine identical slots; which pen is in your hand is a fact about you, not about the slot',
      'The dim on the unselected is a FILTER rather than a second set of colours: nine inks would need nine muted twins, and they would drift from the real ones the first time either was tuned',
      'THE SWATCH THAT OPENS THE PICKER NOW CLOSES IT. Every other way out was already there — Escape, a click anywhere else — except the one the hand reaches for first, which is the thing you just clicked. Without it, clicking again tore the plate down and built an identical one in the same place: a control that visibly does nothing, which is worse than one that does nothing quietly, because you try it twice',
      'ADOPTING-SKEW-1.14.md — what an app already on Skew has to pick up from v1.9.0 to v1.14.0. Not a code drop: every section says what to copy, what it depends on and what it costs, so a team can take three things and skip the rest. Four new primitives, the additive factory API, six behaviour patterns written with the wrong version first because that is the part that transfers, and six traps — substring selectors, the background shorthand, clip-path eating box-shadow, canvases having no pseudo-elements, rebuilding a list from inside an open popup\'s callback, and SVG inner-group rotation',
    ],
  },
  {
    version: '1.14.0',
    date: '2026-08-16',
    changes: [
      'SIX SURFACES ON A TAB STRIP, above the specimen. A drawing is not one fill: the face of a letter, its sides, its shadow and the ground under it are four different marks, and a panel offering one set of hatch settings makes you believe they share them. Each tab carries its own type, pen, spacing, angle, ink and follow — and switching loads all of it, which is the entire reason knob(), fader() and now rotary() expose .set(). A strip that changed a heading and left six controls showing the previous surface\'s numbers would be worse than no strip',
      'THE TABS GO ABOVE THE SPECIMEN, not below it. They are not a control the way the knobs are — they choose WHICH DRAWING the bay is about, and a selector under the thing it selects reads as belonging to it. Everything below the strip is the surface the strip picked',
      'EDIT ALL, on the same bar past a milled channel. It replaced an enable switch that was answering a question nobody asked at the end of a strip about WHICH surface — the useful question there is the opposite one: whether the next change lands on the surface you are on or on all six. Six surfaces means six of every setting, and without it you edit the pen six times and the sixth differs from the first because you mistyped it',
      'ALL spreads ONLY THE FIELD YOU TOUCHED. Copying the whole state would make it mean "make them identical", which is a different and far more destructive thing than "change this one setting everywhere". And it is a LATCH, held down while on, so a knob turned by accident with it engaged is a mistake you can see before you make it',
      'With ALL engaged every tab goes down and lights. Dimming the five you are not on said the opposite of the truth — that they were less involved — when the point is that a change now lands on all six equally. aria-checked still names exactly one, because DOWN is what the change reaches and CHECKED is what the controls are reading, and those stop being the same fact the moment ALL is on',
      'TWO FACTS, TWO GESTURES, TWO CHANNELS. Which surface you are EDITING and whether it is DRAWN are different questions, and the first build ran both through one switch and got both wrong: turning a surface off also meant leaving it, so you could not see what you had turned off and coming back to look turned it on again. Single click selects, double click toggles drawn. DOWN is what the next change reaches; a LIT LEGEND is what gets plotted. A tab can be down and dark — editing something that will not be drawn, which is a real and useful state — or up and lit',
      'And with ALL engaged the double click goes wide too. Edits spreading but on/off not is the kind of half-rule nobody can hold in their head, and the first surface it surprises is the one you stopped looking at',
      'FOLLOW THE OBJECT — optional, and it changes what the Angle knob MEANS. Off, 45° is 45° from the sheet. On, it is 45° from the object, so a letter\'s sides stay lit from the same side however it is rotated and a shadow keeps running across the light instead of drifting into a pattern that fights it. It sits next to Angle and nowhere else, because it is not a seventh setting — it is the units the sixth is measured in, and a toggle that changes what a number means from across the panel is two controls you have to remember are connected. The readout says which: 45° absolute, +45° relative',
      'ALL is a WORD again. As a glyph it was a quarter of the width and cost more than it saved: every other key on that bar is a word, so a lone mark among six names reads as a different KIND of thing rather than the same kind with a wider reach, which is the one thing it must not say',
      'REVERTED — glass shading on the ink swatches. Bright walls, a hard specular and the ink as a core is the correct recipe for a tube and the wrong one for a 28px square, because at that size the two lit walls and the specular are most of the object and the colour is what is left over. On a swatch the COLOUR IS THE POINT, and any treatment that spends the width describing the material has already lost. Recorded in the CSS so the dead end is only walked once',
    ],
  },
  {
    version: '1.13.0',
    date: '2026-08-16',
    changes: [
      'THE ROTARY\'S LEVER IS A KNOB NOW, and the roundness is an argument rather than a style. It was a white teardrop, which has to rotate as a whole — so its lighting rotated with it and "lit from above left" spent half the dial lit from below right. Counter-rotating the shading inside the silhouette fixes the physics and still looks wrong, because the eye reads a moving edge as a moving surface whatever is painted on it. A circle has no orientation, so the cap never turns, its lighting is nailed to the room like every other cap here, and the only thing that moves is the indicator',
      'Four rings and a dot, built outside in: a knurled collar, a lit bevel, a near-flat face, one small bright dot. THE FACE IS ALMOST FLAT IN VALUE and that is the whole difference between machined metal and a plastic bead — a broad radial sheen says the surface is domed and slightly wet, and a real knob\'s top is a turned disc. All the light lives in the edges',
      'Each knurl tooth takes the lamp separately, bright where it faces it and dark where it turns away. That alternation IS the knurl; a uniform ring of ticks is a texture, and textures do not turn in the light',
      'THE INDICATOR IS A DOT, NOT A LINE. A line is a second radius competing with the ring it sits inside; a dot is a position and nothing else, which is all a pointer has ever had to be. 62px, down from the first round build',
      'GLASS SHADING ON THE INK SWATCHES — the same squircle, but it stops being a painted face and starts being a body of ink seen THROUGH something. The walls are the brightest thing on it, which is the counter-intuitive half: the instinct is to darken the edges because that is more colour to look through, true of a solid lump of liquid and false of anything with a WALL. A lit glass wall throws the room straight back, so both edges go white and the colour retreats to the middle',
      'One hard specular left of centre running the full height, because it is on the OUTSIDE of the glass and belongs to the room rather than to the ink. The seated state restates every layer rather than half of one: `background` resets background-image, so declaring only the core would strip the walls and the specular off the one swatch you are looking at — the trap that once erased a knurl. Only the CORE inverts; the room does not move',
      'ANY LIT READOUT TAKES A TYPED VALUE — double-click it. A knob is for LOOKING FOR a value and a keyboard is for KNOWING one, and a panel that only offers the first is one you fight whenever you already have the number. Pen, Spacing, Angle, Count, Attempts, Yaw, Pitch, Roll, Hue, Min stroke, Join reach, Level and Trim',
      'Double-click and not click, because a single click on a readout is what happens on the way to somewhere else and a field that opens by accident eats the next keystroke. Units are formatting, not input — 45 and 45° both work. The window does not become a form control: same lit glass, same phosphor, same tabular figures, a caret and nothing else, and NO I-BEAM on hover, because a text cursor claims it is a text field and it is not — it is a display that will take a value if you ask it twice',
      'The control underneath stops hearing arrow keys while the field is open, or typing into the box also nudges the thing the box reports on. The write happens after the input is removed, because write() repaints the readout and a repaint with the input still in it leaves the field half-torn',
      'FEATURE REQUEST recorded, not built: the ink swatch as a glass capsule, filled or empty. Written up with the prior art — pen cap, nib and pipette were all built and rejected before the squircle, and all three failed the same way, by getting better at being a picture of a thing on the desk and no better at being a control. And with the open question it has to settle first: a slot is binary today, so a three-state capsule needs a third fact to carry or half-full is decoration',
    ],
  },
  {
    version: '1.12.2',
    date: '2026-08-15',
    changes: [
      'PROSE CUT THROUGHOUT physical-ui-layers.html. The page had grown an essay per section — three lede paragraphs where one does the job, and section 07 running to five paragraphs describing a control that is on screen, live, two inches below the sentence describing it',
      'The rule applied: if the demo shows it, do not write it. A dial with six visible positions does not need its six positions listed; a knob with a lit arc does not need the arc described. What survives is the part the picture cannot say — why a ball and not a swatch, why the blob is not optional, why the three knobs stay independent',
      'Section 07 from ~40 lines to 11. Masthead 3 paragraphs to 2, the warning banner halved, sections 01–06 and 08 cut to two or three sentences each, both bill columns tightened, and the fifteen material tiles trimmed of their restatements',
      'No markup, no control and no behaviour touched — text only. Script parses, div count unchanged at 44, mat-count still writes itself',
    ],
  },
  {
    version: '1.12.1',
    date: '2026-08-15',
    changes: [
      'HATCH-API.md — the reference for the fill generators, written because the section that documented them did it in eleven paragraphs of prose. That prose was the right thing to HAVE and the wrong thing to put in front of somebody who wants to use the code: the argument for a choice and the interface to it are two different documents, and only one of them belongs on the page',
      'THE ONE CONTRACT, stated once and in one place: a region is a function tone(x, y) — negative outside, 0…1 inside, 0 bare paper and 1 as dark as the fill goes. That is the entire coupling between what is drawn and how it is filled, which is why any subject that can answer it can be filled by any generator here and no generator ever asks what shape it is on',
      'And the things you only find out on paper: everything is millimetres at 96/25.4 with no pixel below the DOM layer; pitch and nib are ONE setting; four passes at pitch s land the darkest tone at s/4, so s stays four nibs clear of the flood crossing; dither is not optional on a hand fill or the tone bands into isolines of the lighting; the pole trap in latitudes and why aiming the axis down the light hides both blank caps',
      'THE WALL WALK IS WRITTEN UP AS DELIBERATELY NOT IMPLEMENTED, with the reason, so that nobody rebuilds it. It takes a flat fill to one stroke and it was removed — the count is not the drawing, and every trick of that kind buys a lift with a line that cannot be erased. A dead end is only recorded once; after that it is just an absence somebody helpfully fills in again',
      'The page keeps the ultra-basic — the contract, six signatures, one line each — and a door to the file. The reasoning went where it belongs, into the code comments beside the line each paragraph explains, where it cannot go stale without the line going with it',
    ],
  },
  {
    version: '1.12.0',
    date: '2026-08-15',
    changes: [
      'FIX — SERPENTINE WAS NOT SERPENTINE, and it joined in the wrong place twice over. It chained the runs WITHIN one scanline and never joined one scanline to the next: on the ball every scanline has exactly one run, so there was nothing to chain and the result was PARALLEL under another name',
      'FIX — and on the blob, a scanline crossing the hole has two runs, so joining them ruled a line straight through the hole. That is why the shape came out solid. A serpentine is a boustrophedon: the join belongs at the TURNAROUND, end of one pass to start of the next, and a gap inside a pass is a hole, which is exactly where a pen DOES lift. Between lines, connect; within a line, lift. Measured after: 7 movetos for 73 linetos where parallel needs one per line, and zero ink inside the hole on all three machine fills',
      'THE DIAL CARRIES BOTH WORLDS — three machine fills (Parallel, Crossed, Serpentine) and section 08\'s three hands (Hand, Hand cross, Hand random), borrowed rather than reimplemented: a second implementation of a hand would be two hands that drift apart, which is the same argument KIT makes about the ball. One definition, two callers. The bay\'s old machine-made Hand hatched is retired — it broke the register, and noisy is not hand-made',
      'TWO SPECIMENS SIDE BY SIDE, ball left and blob right, and neither is optional. The ball answers what TONE a fill makes; the blob answers what it does when it hits an EDGE — where strokes stop, and what happens in a notch too narrow to fit one in. A fill can pass one and fail the other, so one sheet would let a hand look finished when it cannot turn a corner',
      'And both subjects come from the SHARED KIT now. This section used to light its own sphere, which is the one thing the kit exists to prevent: light the ball differently in 07 than in 08 and every comparison between a machine fill and a hand one is comparing two balls instead of two fills',
      'ALL THREE KNOBS REACH THE HANDS. They did not at first, on the reasoning that a hand\'s pitch and angle ARE the hand — wrong in an instructive way: 08 writes every hand against a BASE, each pitch a multiple of it and each pass angle an offset from it, so the character lives in the relationships and the base is only where they are anchored. Moving the anchor rotates the whole fill or changes its pitch without changing what it looks like, which is the difference between a parameter and a different drawing',
      'Spacing is passed only when it means something: the hands default their pitch FROM THE NIB, so a caller that picks up a bigger pen and says nothing gets the same drawing with a bigger pen rather than a darker one. Handing them a number unconditionally would take that over on every render',
      'One documented dead end survives: hand random has no register to rotate — 08 says a fill with no readable direction is the whole definition of it — so Angle goes quiet on that one position rather than turning and changing nothing. Verified by measurement: spacing moves all three hands, angle moves two of the three and leaves random byte-identical',
    ],
  },
  {
    version: '1.11.0',
    date: '2026-08-15',
    changes: [
      'ONE SECTION, TWO HALVES. 08 is now FILLING — by hand, and by machine — because the two blocks want opposite things from the same job and that is only legible if they are read against each other. They share a rig, so the ball, the lamp and the blob are identical on both sides; the panels sit in one stage with a gap between them. Materials is 09 and the bill is 10',
      'BY MACHINE — THE SERPENTINE, the second half, and it takes the machine\'s side completely: no wobble, no jitter, no drift, exact pitch, straight lines. What it optimises is not the picture, it is THE PEN LIFT — a plotter\'s real cost is not line length, the head moves at the same speed whether the pen is down or up. It is the number of times the pen comes out of the paper, aims, and comes back down, and every one is a chance to blot and to leave the comma a felt tip makes when it lands',
      '3D PRINTERS SOLVED THIS FIRST and the answer is the same in two dimensions: at the end of a pass do not lift, TURN. The next pass runs backwards so its start is where the last one ended, and the two are one stroke with a corner in it',
      'A CONTROL AND A RESULT, side by side, which is the only honest way to show it: left column lifts at the end of every pass, right column turns instead. Same tone model, same pitch, same nib, same drawing, and a lit readout under each — the two numbers are the argument, and they are read off the panel rather than quoted here, because a number in a changelog goes stale the first time the pitch moves',
      'THE COUNT IS NOT THE DRAWING, and this is what the half is actually for. There is a version that gets the flat shape to ONE stroke: route along the outline where the straight cut runs out, then carry on round the perimeter. It works, the readout says 1, it was built — and it is GONE. Every trick of that kind buys a lift with a LINE, and a line is permanent: the wall inks twice where the pen retraces it, and the closing join reaches from wherever the fill happened to stop to wherever the perimeter happened to start, straight across the middle of the shape. One of those ruins a plot. Sixty pen lifts do not',
      'SO THE RULE IS THE CONSERVATIVE ONE: turn where the next pass is genuinely next to you, lift otherwise. A SERPENTINE IS A FILL THAT DOES NOT LIFT WHEN IT DOES NOT HAVE TO, NOT A FILL THAT NEVER LIFTS — and chasing the second is how you draw the first line you cannot erase. Lifting is free; ink is not',
      'THE BLOB HAS A HOLE IN IT NOW, on both halves, because a fill that has never met one has not been tested. Every hard thing about a boundary happens twice as often once the region has an inside edge: passes break in the MIDDLE instead of at the ends, the two halves of a broken pass stop being neighbours, and any join reaching across the gap draws a line through the one place on the sheet meant to stay paper. A fill is not proved by the shape it fills, it is proved by the shape it REFUSES to',
      'AND SHRINK-UNTIL-IT-FITS IS NOT A PLACEMENT. It terminates every time and sometimes terminates at a hole a third of a millimetre across, which is a dot the fill steps over without ever being asked a question. The offset walks back toward the centre and the best attempt wins — over 80 seeds the hole is 5.8 to 15.6mm across and never closer than 2.6mm to the outer edge',
      'THE EDGE IS A HAIRLINE on the machine half — the only line in the section drawn at a width that is not a pen. At the nib\'s own width the outline is the heaviest mark on the sheet and takes the eye every time, which is the one thing a specimen must not do. What plots is the nib; this is the specimen\'s own annotation, and it is thin so that it says so. It is still counted, because a thin line is still a line the pen went down to draw',
      'NEW SHEET on the machine half too, re-rolling the outline and the hole. A seeded fill judged from one shape is a fill judged from nothing',
      'THE PEN WENT UP TO 0.35 and every pitch went up by the same 1.4 with it, which is a change of PEN and not of density — the nib-to-gap ratio is what a hatch looks like, and it is unchanged. 0.25 was a defensible choice and an unreadable one: at 1:1 on a 96dpi screen it is a sub-pixel line, so the fill and the hairline edge arrived at the same weight and neither could be told from the other. The document already says this about the bay — a 0.20 nib LOOKS like a sub-pixel line because that is what 0.20 is — and the fix for a line you cannot see has never been to draw it wrong, it is to pick up a bigger pen',
      'ONE SHEET PER FILL, ball and shape side by side on it with a gap, one row per fill instead of a grid of separate screens. A screen per drawing is the wrong unit: the question a row asks is what ONE fill does to two different problems, so the two answers belong on the same paper — same stock, same pen, same run — and each caption sits under the drawing it is about rather than in a shared strip you have to decode',
      'AND `.flat` WAS ALREADY TAKEN. It is the pale comparison panel in 01 and it carries a 1px WHITE border and a 16px radius; `.hh-field` overrode its background and its shadow by source order and had no reason to mention `border`, so the shape sheet came out wearing a white edge the tone sheet beside it did not have. Two rules that never met, agreeing on everything except the one property neither declared. The file already records this exact lesson — check what the stylesheet says about a name before reusing it — and the fix is not more specificity, it is not taking someone else\'s word: the class is `hh-shape`, and the two segment classes went from `.a`/`.b` to `.hh-a`/`.hh-b` for the same reason before they collided with anything',
      'THE BLOB\'S RADIUS IS DERIVED, not chosen. Its four harmonics sum to 0.65, so the widest point is 1.65 × base — pick base as a fraction of the sheet and about one seed in ten runs off the edge of it. Sized from the worst case with 2.5mm of margin, no seed can',
      'chain() takes a BRIDGE rather than a reach — a function that either returns the line the pen draws on the way, or says no. That is the whole of where the argument lives',
      'NEW SHARED BLOCK — the SPECIMEN KIT. Both halves draw fills and agree about almost nothing, but they must not disagree about THE THING BEING DRAWN: light the ball differently or put a different neck in the blob and the two stop being comparable, which is the only reason either is worth having. scene(), blob(), latitudes(), parallels() and carve() moved out, and each half owns nothing but its own hand',
      'The readout is a .lcd rather than a caption, because it is the RESULT and not a label on one — and the control column\'s is .dim, the off state that is powered rather than dark, which is exactly right for a number that is correct and is not the one being argued for',
      'THE MACHINE BALL PROVES THE HAND\'S CLAIM FOR FREE. Nothing down there is dithered, so the four thresholds show as clean BANDS — the contour map of the lighting that the hands above spend a paragraph avoiding. Both balls are correct; only one of them looks drawn',
    ],
  },
  {
    version: '1.10.0',
    date: '2026-08-15',
    changes: [
      'THE SPHERE TEST — the first block in this document that is not a control. Everything before it is a thing you touch; this is a thing you JUDGE, and the whole of it is three fills drawn twice each with nothing to set.',
      'THREE NEW HANDS: HAND HATCHING, HAND CROSS HATCHING, HAND RANDOM LINES. They are not a re-tune of the bay\'s Hand hatched position — that one breaks the register and stops, which makes a fill look NOISY, and noisy is not hand-made. What a hand does is a list, and every item on it is something a loop does not do',
      'IT DOES NOT SPACE EVENLY, and that is the one that mattered most: an unvarying pitch is a louder machine tell than straightness ever was, so every family is jittered by a third of its own spacing before any wobble is applied. Wobble alone was tried first and reads as a shaky machine',
      'IT DOES NOT COME BACK AT THE SAME ANGLE (each pass drifts a couple of degrees off the last), IT DOES NOT STOP ON THE LINE (a stroke overshoots the boundary or pulls up short, never by the same amount twice), and IT RE-GRIPS — past about 16mm the wrist runs out of travel, so a long fill contains no edge-to-edge strokes at all',
      'TONE IS BUILT BY GOING BACK OVER, not by drawing a grey: four passes, each confined to what is already darker than the last. Every threshold is dithered with noise, because a clean one draws a CONTOUR MAP of the lighting — the fill bands into visible isolines, which is the one thing that never happens by hand',
      'A FLOOD IS NOT A DARK. Four interleaved passes at pitch s put the darkest tone at s/4, so s has to stay four nibs clear of the crossing or the terminator turns into a solid black disc. Same crossing the hatch bay marks in red on its spacing knob, met again from the other side',
      'THE STROKES FOLLOW THE FORM on the ball, built as latitude circles about an axis tilted behind the screen plane — not as a rotated grid. A grid is right for a flat fill and silently wrong on a sphere: it has no idea where the surface turns',
      'THE AXIS IS AIMED DOWN THE LIGHT, which is the geometric problem this block had to solve rather than tune around. Every axis has a pole on the front of the ball and a place where its circles shrink to a point; put either in the middle of the shading and there is a visible whirlpool in the fill. They cannot be removed, only placed — at 20° behind the plane both land near 0.94R, and the light\'s own screen direction puts the highlight at 0.79R. Aim the axis down the light and the blank cap round the pole IS the highlight and the cap opposite it IS the reflected-light rim. Both are places a hand leaves paper anyway',
      'THE BALL IS THE TONE TEST because it is the one shape whose correct answer everybody already knows. Lambert alone draws a shaded DISC — what makes a sphere is the terminator being darker than the silhouette and the table\'s BOUNCE lifting the lower rim, occluded near the contact so the contact itself stays black. The cast shadow is the only thing saying "table"; there is no horizon line, because a drawn line would be a second object competing with the one being tested',
      'A SECOND SPECIMEN PER HAND, and it is not a bonus: a circle has no corner, no neck and no concave anything, so a fill can be perfect on a ball and come apart the first time it meets a real outline. The flat SHAPE carries no shading at all, one density edge to edge, and what is read there is the boundary — where the strokes stop, and whether they stop in a line',
      'COLUMNS ARE HANDS AND ROWS ARE TESTS, which is the only arrangement where both comparisons are adjacent: down a column is one hand against two problems, across a row is three hands against one',
      'EVERY MARK IS GEOMETRY IN MILLIMETRES. No filter, no blur, no fill anywhere in the block — the viewBox is measured off the element at 96/25.4 exactly as the hatch bay measures its own, so a 0.25 nib on screen is a 0.25 nib on paper and the same paths go out to an SVG and onto the plotter with no rescale. That is the only condition under which a specimen is worth looking at',
      'THE SPECIMEN GLASS KEEPS ITS REFLECTION AND LOSES ITS SCANLINES — the one place this block departs from .screen, and not a preference. The haze is a 1-in-3px horizontal rule and the thing behind it is a fill made of rules a few tenths apart; they beat, and the moire lands exactly on the property being judged. A display that adds texture to the specimen is a filter, not a display',
      'ONE PATH ELEMENT PER SPECIMEN, not one per stroke. A plotter reads movetos, not the DOM, and the random hand emits about five thousand of them',
      'Three more .eng engravings — hatching, cross hatching, random lines — each drawn as its own marks rather than as a picture of them',
      'NO CONTROLS, deliberately, beyond NEW SHEET which re-rolls every seed. Three hands are three answers to one question and what is being asked is which is right; a knob on it would invite tuning before judging. Which of the constants become parameters is recorded in FEATURES-REQUEST, not decided here',
    ],
  },
  {
    version: '1.9.0',
    date: '2026-08-15',
    changes: [
      'THE HATCH BAY — the first COMPOUND control in the language. Everything before it is one control on one row, and hatching was five of those: same shape, same green number, nothing saying which one you turn to change how the drawing looks',
      'It is built round a SPECIMEN, because the refs all put the display in among the controls that feed it — the EQ-200 draws the curve its ten faders make. You judge 0,6 by seeing how dense 0,6 is, not by reading it',
      'THE SPECIMEN DRAWS A LIT SPHERE, not a swatch. A rectangle of even hatch shows the SPACING and hides everything else — and what hatching is actually for is TONE: the same pen at the same angle making light and dark by how much paper it leaves. So it draws the subject every hatching exercise starts with, lit from the same corner as the panel, sitting on its own cast shadow. The field grew to 248px and the bay to 520px to give it room',
      'Tone comes out of WHICH PASSES REACH A POINT, not out of pressure: every scanline carries a threshold and only puts ink down where the drawing is darker than that, so light areas are reached by a few passes and dark areas by all of them. The thresholds walk the golden ratio rather than a cycle, so the passes interleave instead of banding into visible tiers — which is the one thing that gives away a machine-made hatch',
      'CROSSED now means what it means on paper: the second pass thresholds live in the top half of the range, so it only works the parts that are still not dark enough. SERPENTINE chains the runs on a pass into one path and draws the connector between them, which is also why a serpentine fill cannot make a clean highlight — the meander has to cross the light to reach the next dark. HAND HATCHED drifts its threshold and sits each pass off its own track, so no two passes agree where a tone ends',
      'A floor of 0.085 on the lit side, because at zero the highlight gets no strokes at all and the ball dissolves into the paper with no edge. A few sparse passes across the light is what a hand does and it is what makes the silhouette read',
      'The rebuild is COALESCED ON A FRAME and nothing more: a tone-driven hatch is tens of thousands of samples and a knob drag fires far more often than the screen refreshes, so the state lands immediately and the drawing is rebuilt once per frame',
      'It was briefly latched to redraw only on RELEASE, to stop the knob going sticky, and that was the wrong trade. A specimen that does not move while you turn the knob is not a specimen, it is a picture you get afterwards — the whole reason the ball is on the panel is to be watched WHILE the value changes, because that is when you can see which way it is going. Dropping frames is a cost worth paying for that; dropping the feedback is not, because the feedback IS the feature',
      'The specimen is SVG in real millimetres — the viewBox is measured off the element and converted at 96/25.4, so one user unit is one mm and what is on screen is what plots. DOM, not canvas: it takes the bay\'s ::after glass for free. That decides hatch only, NOT the gizmo or the screen — the open question at the foot of FEATURES-REQUEST stands',
      'NEW PRIMITIVE — .plate, the language\'s first floating surface. Everything else in the document is bolted into a chassis; this one positions itself against whatever summoned it, sits above the panel and goes away. Same metal as a .box with two differences, both about elevation: a harder and shorter cast shadow, and 1px of black all the way round, because a lifted edge has a dark side wherever the lamp is. Menus, tooltips and the rotary\'s popup inherit it',
      'NEW PRIMITIVE — .picker, and it replaces the one surface the OS still drew. input[type=color] renders its popup in browser chrome and no CSS reaches it, so touching a colour produced a bright system sheet on a machined panel: the exact moment every other primitive exists to avoid. Field behind the same glass as any display, hue on a real fader with the knurled cap and a scale at the six primaries, one lit .lcd window with editable R/G/B and hex instead of three white boxes, eyedropper as a .key that hides itself where the API is absent, and a well of recents built from the same .pencap the ink rail uses. Dark on purpose — a picker is the one place the panel must disappear so the colour can be judged',
      'FIX — a swatch stopped following the picker after the first colour it was given. Filling an empty slot called drawPens(), which threw away every button and built new ones, INCLUDING the element the open picker\'s callback still pointed at. Every later drag then wrote --ink to a detached node: the specimen and the well kept up because they read the data, and the swatch under the cursor froze at whatever it was when the rebuild happened. The rail never needed rebuilding — filling a slot is a class and a custom property on a button that is already correct',
      'FIX — the same handler captured `empty` as a snapshot and outlived it, so once a slot was filled the next click reopened the picker instead of selecting the pen. It reads the state now, not the photograph',
      'THE PICKER\'S WELL SHOWS THE CASE, NOT A GUESS AT ONE. It was seeded with five hard-coded colours, which is the worst of both: they look like they mean something and they mean nothing, and the moment the rail changed they were five stale duplicates of a palette that no longer existed',
      'So the CALLER says what belongs in the well. A picker opened from a rail passes that rail — the other pens in the case, the set you actually reach for, live by definition and passed as a function so it re-reads rather than freezing a copy at open time. A picker opened from nowhere in particular falls back to what has genuinely been picked before, starting EMPTY rather than starting wrong, and the well hides itself until there is something in it',
      'The swatch you are editing is SEATED in the well, exactly as it is in the rail. Two rails of the same object showing the same state the same way is the whole reason it is the same object',
      'The native input is kept as the VALUE and never as the surface, so swapping the picker in changes the caller and nothing downstream. openPicker() is a primitive, not a bay feature: the hatch bay\'s pens call it and its own Materials tile calls it, which is what makes it one',
      'NOT built, and it is the last piece: the plate does not trap focus. Escape and click-outside close it, but Tab still walks into the page behind. Recorded in FEATURES-REQUEST against .plate rather than .picker, because it decides the pattern for every floating surface after this',
      'THE THREE PARAMETERS ARE THREE KNOBS, which is what this document\'s own rule already said — "every slider that sets a quantity became a knob; a length stays a fader". Pen, spacing and angle are three single quantities and none is a span with two ends you compare, so all three were faders in defiance of a rule the page states twice. One row of 46px knobs also costs a third of the height three param strips did',
      'THE TYPE SELECTOR IS THE ROTARY, not a bar of keys: Parallel / Crossed / Hand hatched / Serpentine. A row of keys shows four labels and makes you infer they are one choice; a selector switch has one lever on one detent, so the fact that they are alternatives is in the object rather than in the reading',
      'FOUR HATCH TYPES: PARALLEL, SERPENTINE, CROSSED, HAND HATCHED. They are four different PATHS, not four textures — parallel lifts the pen at the end of every pass, serpentine does not and is one continuous stroke, crossed is a second pass at 90°, hand hatched breaks the register so the fill has no readable direction',
      'The lines are generated in world space and clipped to the sheet (Liang-Barsky) rather than drawn on an over-sized grid and rotated. That is not tidiness: a serpentine IS its turnarounds, and on an over-sized grid every turnaround falls off the paper — it would have rendered as PARALLEL under a different name on the dial. Clipped, every endpoint lands on the boundary where a real fill puts them, and SERPENTINE emits exactly one moveto where the other three emit one per pass',
      'PEN RUNS FREE, 0.1 to 3 mm. It was six detented stops on the argument that a nib is one of six objects in a case — true of a technical pen, false of this panel: what is being set here is a STROKE WIDTH, and a stroke width is a quantity like any other. A kit is the right model for choosing a pen off a shelf and the wrong one for dialling a line until it looks right, which is what a specimen in front of you is for',
      'The dot that showed the nib at true relative size went with it. At 0.1mm it is a speck and at 3mm it no longer fits a label row — a scale that only works across one octave is not a scale',
      'PEN, SPACING AND ANGLE ARE INDEPENDENT. An earlier build had the pen drag spacing along to hold a nib ratio — a tidy idea and the wrong one, because it means one control silently edits another and a value you set by hand stops being the value you set. Three settings, three knobs, no hidden wiring',
      'SPACING UNDER THE NIB IS NOT REPORTED, because it is not an error. The strokes overlap and the sheet fills solid on its own — that is a fill, and a fill is something you ask for. An earlier build lit a red legend and turned the spacing arc red, framing a legitimate result as a fault; the specimen already shows exactly what happens, which is the whole job of a specimen',
      'THE GROUND IS PAPER NOW. It was near-black, which worked for exactly as long as the ink was orange — and the case has BLACK in it, which is the pen you own most of. Black on black is nothing and grey on black is worse, because it looks like it is working. Same argument the colour picker entry makes: the surface a colour is judged against cannot compete with it',
      'THE INK RAIL IS A CASE, so it is full of SLOTS — three pens it ships with (black, grey, white) and six empty ones. A rail that stops after the pens you happen to have reads as a list that ran out; a case reads as a case, and an empty slot is an invitation rather than an absence',
      'AND EVERY SLOT IS REFILLABLE, including the three that ship full. Black, grey and white are what a case comes with, not what it is stuck with — a swatch you cannot change is a swatch lying about being a pen. The fixed/refillable split is gone and the engraved notch that marked it went too: a mark that is on everything marks nothing. What still separates a slot from a pen is whether there is anything IN it, which the well says by itself',
      'AN EMPTY SLOT IS A HOLE, not a faded pen. The wrong build is a cap at low opacity, which reads as broken or disabled — a slot with nothing in it is a piece of the CASE: a shallow milled well, shorter than a cap because no cap is standing in it, with the same two hairlines every other recess has, and no colour at all because it does not have one yet. It lights its own rim on hover rather than lifting, because a hole cannot come towards you',
      'Empty opens the picker on the FIRST click, because there is no pen to choose yet — filling it is choosing it. A filled slot selects first and refills on the second, so choosing a pen never costs a plate. The slots are spread rather than packed, so the rail ends where the panel ends however many pens are in it',
      'THE STOCK IS TONED (#BEB5A3), because the case has a WHITE pen in it. White on cream is not a subtle result, it is no result — the sheet would look broken rather than look like white ink. Toned stock is what you reach for when you plot white, and it is the one ground where black, grey and white all read at once: contrast against the sheet is 8.7 / 2.9 / 2.0, and grey separates from both its neighbours',
      'fader() exposes .set(), the handle knob() already had, so one control can move another',
      'THE INK SWATCH IS A CAP WHOSE FACE IS THE COLOUR — and it took three wrong objects to get there. A pen cap read as a battery. A nib read as a marker tip. A glass pipette read as a pipette and was still wrong, because all three were the same mistake: each got better at being a PICTURE of a thing on the desk and none got better at being a CONTROL',
      'A rail of little drawings is an illustration. You cannot tell at a glance which one is selected, the colour fights a silhouette for attention, and at 17px the object being depicted is unreadable anyway. So the swatch stopped depicting the pen: the colour gets the whole face, and the state is the same up/down every switch and piano key on the panel already uses',
      'IN USE IS IN — AND IT DOES NOT FALL. Same decision the small piano keys already made: at 28px there is no room for the drop to be legible as a drop, so the movement goes and the state stays. The recess and the chamfer say pressed; hover lights a rim rather than moving anything, the way every key on this panel changes colour under the pointer rather than position',
      'And the pressed recipe is the KEY\'S OWN, applied to a coloured face: the cap keeps its own colour and the gradient INVERTS — dark at the top, light at the bottom, because the bezel is now shading a face that has dropped below it and what light reaches it bounces up off the well. Nothing is tinted, so the swatch you press and the one held down are recognisably the same object in two positions. That is the rule the key learned three times and it did not need learning a fourth',
      'AND THE LAMP, which is the other half of latched — down AND lit is what separates "held by a finger" from "held by the mechanism". Every other latching control here says it with a warm GLYPH and a colour swatch has none: the face IS the legend, and tinting it orange would be lying about the ink. So the lamp goes into the WELL — a tight warm line at the cutout and a short bloom off it, which is light escaping round a seated cap',
      'It is the PANEL\'S lamp colour and not the ink\'s, deliberately: an indicator that changed colour with the thing it indicates stops being an indicator. Held to the source\'s own limit for a latched control — a little light in the well, not a bloom on the chassis',
      'MODELLED, NOT FLAT, which is the only thing separating it from the soft pastel swatch it is shaped like: light from above left at 158°, a hairline of light on the top edge and a dark one under it, and the specular OFF CENTRE because a centred highlight reads as a sticker',
      'Min stroke and Join reach went into a recess below the fold. They are set once per plotter; five identical rows was itself most of why the panel was sad',
      'NEW PRIMITIVE — .eng, the engraved ICON. The language had engraved TYPE and nothing engraved that is a SHAPE, so every icon was a flat monoline glyph laid on the metal: the sticker failure the file already names about a centred highlight. Stroke in the panel\'s shadow colour, one 1px light line under it, never white and never currentColor — an engraving does not change colour when its row is selected, because it is a hole. Six of them so far; every label row in the language can have one now',
      'knob() takes an optional detents array — the angle knob notches at 0 / 45 / 90 / 135 / 180. Same idea the centre fader already had: an angle of 45° is a place, not a value you approach',
      'REMOVED the SLIDER → KNOB A/B card from 04. Sections renumbered: the hatch bay is 07, Materials 08, the bill 09',
    ],
  },
  {
    version: '1.8.0',
    date: '2026-08-15',
    changes: [
      'MATERIALS stops over-claiming. The lede promised that nine primitives carry all six components and that every control on the page is one of them at a size — a completeness claim nobody re-counts when they add a tile, and it read "nine" while the grid held thirteen',
      'The count is now written by the tiles themselves. Adding an entry to the array is the only edit there is; the sentence cannot drift again',
      'Three primitives that were on the page and had no tile: READOUT (the .lcd, used 4× — a lit window cut into the case, phosphor digits, and .dim as an off state that is powered rather than dark), MICRO KEY (22px and recessed, because duplicate and delete must not invite the thumb; delete is the only red in the document and only on hover), KNURLED CHEVRON (the thing you flick — shown at its real 20px, since the knurl is tuned against an 11px glyph and enlarging it would show a texture the document does not have)',
      'Both new key tiles are live for the same reason the fader ones are: a micro key\'s whole content is its hover and a chevron\'s is its flick, so a static sample shows the half that does not matter',
      'The knob/fader rule was stated once, in a comment under .knob, and was therefore invisible from the section built to teach the primitives — a reader concluded the language\'s answer to a slider is "turn it into a knob". It is in the knob tile now: a quantity is a knob, a length stays a fader',
      'FIX — .chev had no position:relative, so the chamfer ring that .chev.open::after draws resolved against .row and was clipped away by its overflow. The one control the chamfer rule names by name was the one control not getting one',
    ],
  },
  {
    version: '1.7.0',
    date: '2026-08-15',
    changes: [
      'The fader family, from the refs: the EQ-200, the TX-6, the K.O.II and the Sidekick are all banks of ONE-cap faders, and the document only had the two-cap range one, which is the exception, not the type',
      'fader() — one factory, three forms, because they differ in two things only: where the lit fill starts and which way the slot runs. LEVEL fills from the end of the slot to the cap. CENTRE fills from the middle out to whichever side, for a value that is an offset rather than an amount. VERTICAL is the same control stood up, with the readout on top and the legend at the foot',
      'The centre form DETENTS: inside 3% of the middle the cap snaps to zero and the scale carries a full-height tick there, the way a real centre-detent pot has a notch cut in its track. Zero is a place you can find without looking',
      'All three share the range fader\'s geometry — a cap centre at t sits at t*100% - (t-.5)*17px — so a cap stays inside its slot at both ends without the value lying about where it is. Track takes every pointer event and the cap comes to the click; wheel and arrows work, shift for fine',
      'Three material tiles for them: FADER · ONE CAP, FADER · CENTRE DETENT, FADER · VERTICAL BANK (three of them, since the reason vertical exists is that a bank of caps makes a profile you read across)',
    ],
  },
  {
    version: '1.6.1',
    date: '2026-08-15',
    changes: [
      'The bright skin came back in the 1.6.0 commit and is removed again: 296 lines of [data-skin="light"], the .skin-switch rules, the empty switch element (its script had already gone, so the page was rendering a stray fixed well top-right) and the restored skin() IIFE that sat directly under the comment explaining why it was gone',
      'MATERIALS was missing the fader, the one control the lede promises by name: every slider that set a quantity became a knob, except a length, which stays a fader. It is there now, live, built by the editor\'s own rangeFader with the same numbers',
      'Its tile spans two columns. A fader sampled in a 232px column leaves the track about 90px once the label and the readout are in, which is not a length, it is a stub. Tiles take an optional class as a fourth field for this',
      'NOTE: physical-ui.css.bak is tracked and still contains the whole bright skin. It is a 1750-line copy of the pre-rename build; left alone here because another agent may be relying on it, but it is where the light mode will come back from next',
    ],
  },
  {
    version: '1.6.0',
    date: '2026-08-15',
    changes: [
      'The bright skin is removed — 336 lines of [data-skin="light"] overrides, the DARK / LIGHT switch and its script. Every effect in this document is light modelling against a dark body: a cap is lighter than its case, a well is darker, and a recess is made by taking light away. That cannot be inverted, only rewritten, so the pale build was a second set of hand-tuned numbers drifting from the first every time either was touched. One material, one set of numbers',
      'The exploration keeps its external stylesheet: physical-ui.css stays a file, dark only',
      'The piano wells (page switcher and editor tabs) get the floor the bay was given back at 1.4 and never shared: #17191d → #1e2126 instead of near-black. A key\'s skirt is #0d0e10, so on a #0a0b0d floor the one part that proves a cap has a body was invisible and the key read as a grey rectangle printed on black. Inset shadow softened to .8 to match',
      'The language has a name: SKEW. It is the word the hand types when it means skeuomorphic, and it is also the trick itself — a flat plane tilted into depth, lit from one lamp above left, nothing actually raised. In the page as targz-skew-design-system',
      'The MOMENTARY VS LATCHING tile was two spans wearing the key classes, under a caption promising that one springs back and the other holds: a sample that could not do the thing it was a sample of. They come from the same key factory as the nav bar now, and both work',
      'Its glyphs were 24px in a 38px cap, leaving 7px of face — on the lit one the sun\'s rays ran into the walls and the orange stopped reading as a legend and became the button\'s colour. 18px now, the nav bar\'s 16-in-34 ratio at this size',
      'The MILLED WELL material tile was demonstrating the fault it documents: the tile stage was #101114, darker than the well cut into it, so the sample was a lighter rectangle on a dark ground. The stage is case metal now, the well sample carries the real recipe, and the caption states the floor rule',
    ],
  },
  {
    version: '1.5.1',
    date: '2026-08-15',
    changes: [
      'Tool palette: keys were 5px apart, which is not 5px of daylight — each raised cap lays a 3px hard skirt plus its blur underneath, and a pressed cap drops 2px further into the gap below it. Pan / Turn / Select were touching. Now 10px, in line with the keypad\'s 11px between stacked rows, and the palette padding goes 7 → 8px so the outer margin does not read as tighter than the inner one',
      'TOOL caption sits 6px above the first key rather than 4px, so the label is not closer to the key than the keys are to each other',
      'Editor tab strip had the same fault worse: 3px between tabs, each laying a 2px skirt, so Letters / Place / Size / Drop / Shade were one object with lines drawn on it. 7px now, and the strip padding 4 → 5px',
      'The editor tab no longer travels. A 26px cap falling into a strip this tight puts its shadow on the neighbour, and there is no room for the fall to read as a fall — it still goes in (recess, chamfer, lamp), it just does not move',
    ],
  },
  {
    version: '1.5.0',
    date: '2026-08-15',
    changes: [
      'Physical UI exploration: the pressed recipe is now two tokens in :root — --recess (the four sharp walls plus the lit lip) and --chamfer (the directional, concave-polarity ring). Five copies of it across switches, keys, tabs, chips and chevrons was five things that drift apart the next time one is tuned',
      'Every toggle in the document now uses it: layer switches, stroke switches, the ALL masters, nav bar latches, editor tabs, the page switcher, view keys, folder chips and chevrons. None declares a fill — each inherits its own raised face, so a pressed cap stays the same object as the cap beside it',
      'Travel normalised: 2px on the big keys, 1px on the small. A tab falling 4px was travelling further than the gap to its neighbour',
      'Fixed: .keypad .pkey and .piano.sm .pkey re-declared box-shadow at the same specificity as the pressed rule but later in the file, so the view keys and editor tabs kept their RAISED shadow when down and only the label changed colour. The size overrides are scoped to :not(.is-down):not(:active) now',
      'Fixed: .chev.open\'s box-shadow ended in a stray comma, making the whole declaration invalid — the open chevron had had no shadow at all',
      'Toggles get the momentary key\'s actuation surge when they engage, and only when they engage: flipping a switch off is a circuit opening, there is nothing to surge. Reuses the same keyframe rather than a second one, since two nearly-identical surges read as one done badly',
      'Pan / Turn / Select moved out of the viewport into their own tool palette. Everything else in that panel answers where the camera is; those three answer what the mouse does, which stays true while you are not looking at the viewport at all',
      'Focus: removed eleven accent outlines and answered :focus-visible explicitly — deleting them had only uncovered Chrome\'s own white-blue default. One hairline everywhere, 1px in the panel\'s orange, plus a brightness lift on the control itself',
      'Removed the colour dot from numbered layer rows; the ALL row keeps its jewel, which wears the whole palette',
    ],
  },
  {
    version: '1.4.2',
    date: '2026-08-15',
    changes: [
      'Physical UI exploration: the chamfer round a pressed switch is now a ring with a direction, not a hairline. A cutout edge is broken all the way round and is not equally lit anywhere — it flares where it faces the lamp and dies as it turns away — and a box-shadow, being the same value the whole way round, always reads as a drawn outline instead',
      'Corrected its polarity, which was the actual bug: the ring was bright top-left and dark bottom-right, which is a DOME. A chamfer diving into a hole is the opposite — its upper edge tilts away from the light and sits in shadow, its lower edge tilts toward it and catches. It was also arguing with the walls inside the cap, which were already right, and a bevel saying "out" wrapped around a recess saying "in" resolves as a raised button every time',
      'Pressed shadow +20% in geometry (offsets and blur, alphas untouched), and the pressed legend is back to full size',
      'Removed the colour dot from numbered layer rows — the light pipe on the leading edge is the same fact, said better and 6px away. The ALL row keeps its jewel, which wears the whole palette',
    ],
  },
  {
    version: '1.4.1',
    date: '2026-08-15',
    changes: [
      'Physical UI exploration: the pressed switch rebuilt. It declares no fill of its own — it inherits the raised cap\'s, so up and down cannot drift apart, and the recess is drawn entirely by inset walls. Every earlier attempt at a separate pressed colour was drawing shade with paint, and a darker cap has nothing left for a shadow to take away',
      'Raised the cap into real grey. Shadow is a difference, and a near-black face left the recess nowhere to fall — the change that makes the pressed state read is a change to the unpressed one',
      'Shadow on all four walls, not just the top: a hole has sides, and at 24px the sides are most of what you see of it',
      'Sharpened it — blur radii 6-12px down to 1-4px. A wall two pixels from the face cannot throw a shade that has softened over that distance; 12px of blur at full black is a cap sitting in fog',
      'Travel down to 1px. Two was a third of the row gap, enough that toggling looked like the row twitched',
      'The legend scales to 0.9 when the cap is down — a face further from the eye subtends a smaller angle. Too small to notice as a change, which is the point',
      'One legend per switch: the plain drawing at normal weight, never struck through or greyed. The cap position already says on or off, and a slashed grey icon reads as disabled',
      'MIXED is now the pressed state with a WHITE legend, not an intermediate height. A master whose column is half on is not half-pressed — the thing it commands is engaged, just not everywhere. Down means it is happening; the colour says how completely, and white against orange is a brightness difference that survives with no colour vision',
      'Brightened the bay, the stroke strip and the row faces to match. A recess is the case seen deeper, not a hole into space — darker than the surface, not black, with the inset shadow doing the work',
      'Rotary selector: removed the detent tick marks entirely. The tip already says where the switch is, and a second mark a few pixels away is another thing to read at the moment you are reading the tip',
      'Knobs and the selector now turn clockwise on a downward drag, and the wheel follows; arrow keys stay conventional so the ARIA slider contract holds',
    ],
  },
  {
    version: '1.4.0',
    date: '2026-08-15',
    changes: [
      'New document explorations/physical-ui-layers.html — a "what if the language were hardware" study. It is an EXPLORATION, not part of the system: index.html is untouched and none of these tokens exist there',
      'Six shipping components redrawn in the skeuomorphic register, each with its real anatomy: the Portrait-Typo layer dock (lifted control-for-control from its ui.js), the nav bar, the page switcher, the layer editor, the viewport and a Launchpad project card',
      'Buttons are objects with a body: a skirt, a cast shadow and real travel. Momentary keys spring back and pulse once; latching keys hold the same position a finger would, which is the distinction flat UI has no way to make',
      'Latched, pressed and open all share one recipe — the cap keeps its own colour, the gradient inverts, a hard black inset runs along the top and a hairline of light along the bottom, and only the legend lights. Three-state switches sit at three physical heights (up / half / down), so the state reads in greyscale',
      'One legend per switch: the plain drawing at normal weight, never struck through or dimmed, since the cap position already says on or off and a slashed grey icon reads as disabled',
      'Sliders that set a quantity became knobs — 270° of travel, an SVG-stroked value arc (a conic gradient behind a CSS mask aliases on three edges), a pointer, drag/wheel/keys, and a bipolar mode that grows from 12 o\'clock. Drag down turns clockwise',
      'Zone from / Zone to became ONE range fader, because the value is one length: cut slot, engraved scale, two waisted caps that cannot cross, a hatched band between them',
      'The Place-from dropdown became a rotary selector: a pale teardrop lever, positions fanned into 76° with their names as a vertical list, leader lines absorbing the angle mismatch',
      'The editor panel bulges around that selector — rounded rectangle unioned with a lobe and joined by tangent fillets, as one clip-path on one element, so the fill cannot seam. Its drop shadow is a filter on a wrapper, because a box-shadow is cast by the border-box and would cut the bulge in half',
      'Glow is spent only on things that emit: light pipes, LED readouts and the big illuminated action keys',
      'Closes with the bill — what the language buys, and what it costs (dark-only, paint cost per row, small type against grain, and that it out-shouts the drawing)',
    ],
  },
  {
    version: '1.3.0',
    date: '2026-08-06',
    changes: [
      'Canvas, grid & rulers (section 03): replaced the static "warm grid" description with how it actually works — the grid is derived from the sheet, not a fixed 40px CSS pattern',
      'Documented the division formula round(max(canvasW, canvasH) / 60) clamped to 4-30, so grid lines always land on the paper edges and continue to the window edges',
      'Documented the size readout: bottom and right rulers pinned to the sheet, a tick per division but only the two ends labelled, in millimetres',
      'Recorded that the Y axis is inverted (paperH - mm) so the origin is bottom-left, matching the plotter bed',
      'Added a demo showing an A1 square sheet at 594 x 594 mm with its grid and both rulers',
    ],
  },
  {
    version: '1.2.0',
    date: '2026-08-06',
    changes: [
      'Side panel (section 06): rewritten as a Tweakpane 4 spec — the hand-drawn panels were never Tweakpane, which is what every app actually ships. Adds a prominent "do not hand-build this" callout, a faithful replica of a skinned pane, a widget anatomy table mapped to the --tp-* variables, placement rules, and the full skin block to copy',
      'Nav bar (section 07): replaced the old Bottom Dock with the glass nav bar as actually shipped — 40px items, popover menus with kbd shortcuts, separator, status readout — plus a full spec list',
      'Logs (section 10): the log is now an event, not a surface — silent by default, a transient toast above the nav bar, and an on-demand history in a nav bar popover, with repeat collapsing, dwell rules and an unread dot',
      'Tab bar (section 11): added the white pill page switcher — demo, spec and states. Active is an --tg-orange-soft fill with an --tg-orange label; focus is a 3px orange halo, never the browser default',
      'Section 11 renamed to "Tab bar & app header"; the docked app header is kept for windowed tools',
      'Console is now bright — white surface, hairline border, orange $ prompt — instead of the black block',
      'Scoped the console to streamed output from external processes (vpype, plotter drivers)',
      'Added a contents rail with scroll-spy, built from the sections at runtime',
      'Added glass tokens: --tg-glass, --tg-glass-border, --tg-glass-hover, --tg-shadow-float, --tg-shadow-pop',
      'Everything else in the document is unchanged',
    ],
  },
  {
    version: '1.1.0',
    date: '2026-05-01',
    changes: [
      'New design system created with Claude design (targz Design System.html)',
      'Remove previous design-system.html (no longer relevant)',
    ],
  },
];
